import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "vinext on Cloudflare Workers",
  description: "Generated by create-vinext-app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Kaisei+Opti:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="m-0 p-0">
        {children}
      </body>
    </html>
  );
}
